name: CMake Build and Test

on:
  push:
  pull_request:
jobs:
  build_and_test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
           apt-get update
           apt-get install -y build-essential cmake libgtest-dev 

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ./build
        run: cmake ..

      - name: Build project
        working-directory: ./build
        run: cmake --build . --config Release

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure